E-Commerce/Controllers/ApplicationTypeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccess.Data;
using Microsoft.AspNetCore.Authorization;
using Models;
using Utility;
using DataAccess.Repository.IRepository;

namespace E_Commerce.Controllers
{
    [Authorize(Roles = WebConstant.AdminRole)]
    public class ApplicationTypeController : Controller
    {
        private readonly IApplicationTypeRepository _appTypeRepo;

        public ApplicationTypeController(IApplicationTypeRepository appTypeRepo)
        {
            _appTypeRepo = appTypeRepo;
        }


        public IActionResult Index()
        {
            IEnumerable<ApplicationType> objList = _appTypeRepo.GetAll();
            return View(objList);
        }


        //GET - CREATE
        public IActionResult Create()
        {
            return View();
        }


        //POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ApplicationType obj)
        {
            if (ModelState.IsValid)
            {
                _appTypeRepo.Add(obj);
                _appTypeRepo.Save();
                TempData[WebConstant.Success] = "Action completed successfully";
                return RedirectToAction("Index");
            }
            return View(obj);

        }


        //GET - EDIT
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _appTypeRepo.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ApplicationType obj)
        {
            if (ModelState.IsValid)
            {
                _appTypeRepo.Update(obj);
                _appTypeRepo.Save();
                TempData[WebConstant.Success] = "Action completed successfully";
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        //GET - DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _appTypeRepo.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //POST - DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _appTypeRepo.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }
            _appTypeRepo.Remove(obj);
            _appTypeRepo.Save();
            TempData[WebConstant.Success] = "Action completed successfully";
            return RedirectToAction("Index");


        }

    }

}

E-Commerce/Views/ApplicationType/Create.cshtml
@model ApplicationType


<form method="post" asp-action="Create">
    <div class="border p-3 bg-white">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group row py-2">
            <h2 class="text-info pl-3">Add ApplicationType</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control"/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
              
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">
                                <i class="fas fa-sign-out-alt"></i>  Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>

E-Commerce/Views/ApplicationType/Delete.cshtml
@model ApplicationType


<form method="post" asp-action="DeletePost">
    <div class="border p-3 bg-white">
        <input asp-for="Id" hidden=""/>
        <div class="form-group row py-2">
            <h2 class="text-info pl-3">Delete Application Type</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled class="form-control"/>
                        
                    </div>

                </div>
            
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">
                                <i class="fas fa-sign-out-alt"></i>  Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>

E-Commerce/Views/ApplicationType/Edit.cshtml
@model ApplicationType


<form method="post">
    <div class="border p-3 bg-white">
        <input asp-for="Id" hidden=""/>
        <div class="form-group row py-2">
            <h2 class="text-info pl-3">Edit Application Type</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control"/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
               
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">
                                <i class="fas fa-sign-out-alt"></i>  Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>

E-Commerce/Views/ApplicationType/Index.cshtml
@model IEnumerable<ApplicationType>



<div class="container p-3 bg-white">
    <div class="row" pt-4>
        <div class="col-6">
            <h2 class="text-primary">Application Type List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-action="Create" class="btn btn-primary">
                <i class="fas fa-plus"></i> &nbsp;  Create New Application Type

            </a>
        </div>
    </div>
    
    
    
    <br/><br/>
    
    @if (Model.Count() > 0)
    {
        <table class="table-bordered table-striped" style="width: 100%;">
            <thead>
            <tr>
                <th>
                      Name
                </th>
               
                <th></th>
            </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                <tr>
                    <td width="50%">@obj.Name</td>

                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="ApplicationType"  asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-primary mx-2">
                                <i class="fas fa-edit"> &nbsp; </i> 
                            </a>
                            <a asp-controller="ApplicationType" asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger mx-2">
                                <i class="far fa-trash-alt"></i> 
                            </a>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>

    }
    else
    {
        <p> No Application type exists</p>
    }

</div>